version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # Using deploy with native GPU support if available
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 2G
    # Optional: Uncomment the following lines if you want to use NVIDIA GPU
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped

  llm-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped

volumes:
  ollama_data:
